name: build
on:
  pull_request:
  workflow_call:
  push:
    branches:
      - '**' # filter on branch to prevent tag pushes from triggering this workflow


jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Determine and checkout branch
        id: determine_branch
        run: |
          RAW_BRANCH=$(git branch -r --contains ${{ github.ref_name }} | grep -v HEAD | grep origin | head -n 1)
          BRANCH_NAME=$(echo $RAW_BRANCH | sed -e 's/^[[:space:]]*origin\///')
          echo "Found branch: $BRANCH_NAME"
          echo "branch=$BRANCH_NAME" >> $GITHUB_OUTPUT
          git checkout $BRANCH_NAME

      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: build
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/
