name: build
on:
  pull_request:
  workflow_call:
    inputs:
      branch:
        type: string
  push:
    branches:
      - '**' # filter on branch to prevent tag pushes from triggering this workflow


jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          ref: ${{ inputs.branch || github.ref }}

      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: build
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/
