name: pre-release
on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  determine-branch:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.determine_branch.outputs.branch }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine and checkout branch
        id: determine_branch
        run: |
          RAW_BRANCH=$(git branch -r --contains ${{ github.ref_name }} | grep -v HEAD | grep origin | head -n 1)
          BRANCH_NAME=$(echo $RAW_BRANCH | sed -e 's/^[[:space:]]*origin\///')
          echo "Found branch: $BRANCH_NAME"
          echo "branch=$BRANCH_NAME" >> $GITHUB_OUTPUT

  call-build:
    needs: determine-branch
    uses: ./.github/workflows/build.yaml
    with:
      branch: ${{ needs.determine-branch.outputs.branch }}

  create-release:
    needs: [ determine-branch, call-build ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.branch || github.ref }}

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: Artifacts
          path: build/libs/

      - name: Generate Changelog with git-cliff
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: config/cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG.md
          files: build/libs/*.jar
          draft: true

      - name: Commit changelog
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Update changelog [skip ci]"
          branch: ${{ needs.determine_branch.outputs.branch }}
          commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
