name: release
on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  call-build:
    uses: .github/workflows/build.yaml

  create-release:
    needs: call-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: Artifacts
          path: build/libs/

      - name: Generate Changelog with git-cliff
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: config/cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG.md
          files: build/libs/*.jar

      - name: Commit changelog
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update changelog
